import { HttpHeaders } from "@angular/common/http";

export const headers = new HttpHeaders({
      'Content-Type': 'application/json; charset=utf-8',
     'Access-Control-Allow-Origin': '*',
        });
        export const validationMessages = {
            email: [
              { type: 'required', message: 'Email is required.' },
              { type: 'pattern', message: 'Enter a valid email.' }
            ],
            password: [
              { type: 'required', message: 'Password is required.' },
              { type: 'minlength', message: 'Password must be at least 5 characters long.' }
            ],
         
        
           };
        
//  week day list 
export const weekDayList = [
  'January',
  'February',
  'March',
  'April',
  'May',
  'June',
  'July',
  'August',
  'September',
  'October',
  'November',
  'December'
]

export const  bibileBooks: Array<string> = [
  'Genesis',
  'Exodus',
  'Leviticus',
  'Numbers',
  'Deuteronomy',
  'Joshua',
  'Judges',
  'Ruth',
  '1 Samuel',
  '2 Samuel',
  '1 Kings',
  '2 Kings',
  '1 Chronicles',
  '2 Chronicles',
  'Ezra',
  'Nehemiah',
  'Esther',
  'Job',
  'Psalms',
  'Proverbs',
  'Ecclesiastes',
  'Song of Solomon',
  'Isaiah',
  'Jeremiah',
  'Lamentations',
  'Ezekiel',
  'Daniel',
  'Hosea',
  'Joel',
  'Amos',
  'Obadiah',
  'Jonah',
  'Micah',
  'Nahum',
  'Habakkuk',
  'Zephaniah',
  'Haggai',
  'Zechariah',
  'Malachi',
  'Matthew',
  'Mark',
  'Luke',
  'John',
  'Acts',
  'Romans',
  '1 Corinthians',
  '2 Corinthians',
  'Galatians',
  'Ephesians',
  'Philippians',
  'Colossians',
  '1 Thessalonians',
  '2 Thessalonians',
  '1 Timothy',
  '2 Timothy',
  'Titus',
  'Philemon',
  'Hebrews',
  'James',
  '1 Peter',
  '2 Peter',
  '1 John',
  '2 John',
  '3 John',
  'Jude',
  'Revelation'
]

export const typeOfDay = [
  'Mercy Day Service',
  'New Moon Service',
  'Power Day Service',
  'Glorious Service',
  'Passion week (Monday)',
  'Passion week (Tuesday)',
  'Passion week (Wednesday)',
  'Passion week (Thursday)',
  'Good Friday',
  'Palm Sunday',
  'Passion week (Saturday)',
  'Easter Monday',
  'Easter Sunday',
  'Remembrance of Pastor Founder',
  'Pastor Founder Remembrance',
  'Xmas Eve',
  'New Year Eve',
  'New Year Day',

]

export const currentDayDate = [
  "1st",
  "2nd",
  "3rd",
  "4th",
  "5th",
  "6th",
  "7th",
  "8th",
  "9th",
  "10th",
  "11th",
  "12th",
  "13th",
  "14th",
  "15th",
  "16th",
  "17th",
  "18th",
  "19th",
  "20th",
  "21st",
  "22nd",
  "23rd",
  "24th",
  "25th",
  "26th",
  "27th",
  "28th",
  "29th",
  "30th",
  "31st",
]

export const dayOfTheWeek = [
  "Monday",
  "Tuesday",
  "Wednesday",
  "Thursday",
  "Friday",
  "Saturday",
  "Sunday",
]